#!/bin/sh

RNG="$1"
JAR=${MSV:-msv.jar}

if [ ! -f "$JAR" ]; then
    echo "Please set the MSV environment variable to point to msv.jar obtained from https://msv.dev.java.net/"  
    exit
fi

shift

for s in "$@"; do
  cat=cat
  if [ "${s%.gz}" != "$s" ]; then
     cat=zcat
  fi
  $cat "$s" | java -jar "$JAR" "$RNG" /dev/fd/0 |grep -Ev '^relmes verifier|^parsing|^validating|^start parsing|^\s*$|^the document is valid' | sed "s!line:\([0-9 ]*\), column:\([0-9 ]*\) of file:///dev/fd/0!$s:\1:\2!g" |sed "s,file:///dev/fd/0,$s,g"
done
