#!/bin/bash

RNG="$1"
shift

for s in "$@"; do 
  # xmllint is much faster but line numbers it reports
  # are rather misleading
  # jing is slow, consumes too much memory, but reports
  # line numbers accurately
  (xmllint --noout --relaxng "$RNG" "$s" >/dev/null 2>&1) ||\
  (in=<(zcat -f "$s") sh -c "jing '$RNG' \$in 2>&1 | sed \"s%\${in}%$s%g\"")
done
